MESSAGE_RECEIVED = "MESSAGE_RECEIVED"

INTENT_DETECTED = "INTENT_DETECTED"

FLOW_EXECUTED = "FLOW_EXECUTED"

PROSPECT_CREATED = "PROSPECT_CREATED"

CRM_UPDATED = "CRM_UPDATED"

RESPONSE_GENERATED = "RESPONSE_GENERATED"
